baseURL: "https://mahdyiar.github.io/"
theme: "hyde-hyde"
publishDir: "docs"

DefaultContentLanguage: en
languages:
  fa:
    languageCode: "fa-ir"
    languageName: "فا"
    title: "مهدیار جلالیان"
    languagedirection: rtl
    layoutReverse: true
    weight: 2
    menus:
      main:
      - name: "رزومه"
        weight: 200
        url: "/resume/"
        identifier: "resume"
      - name: "تماس"
        weight: 250
        url: "/contact/"
        identifier: "contact"
    params:
      author: "مهدیار جلالیان"
      title: "وبلاگ شخصی مهدیار جلالیان"
      description: |
        FrontEnd Developer
        ____________________
        همراه : 09307344268 
        سن: 22
        
  en:
    languageCode: "en-us"
    languageName: "en"
    title: "Mahdiyar Jalalian"
    weight: 1
    menus:
      main:
      - name: "My Resume"
        weight: 200
        url: "/resume/"
        identifier: "resume"
      - name: "Contact Me"
        weight: 250
        url: "/contact/"
        identifier: "contact"
    params:
      author: "Mahdiyar Jalalian"
      title: "Mahdiyar Jalalian Personal Blog"
      description: |
        FrontEnd Developer 
        ____________________
        (+98) 930 734 4268
        Age: 22

params:
  authorimage: "/img/MahdiyarJalalian.jpg"
  mainSections: "posts"
  highlightjs: true
  highlightjsstyle: "github"
  postNavigation: false
  since: "2025"
  copyright: "| Mahdiyar Jalalian"
  social:
    github: "Mahdyiar"
    linkedin: "mahdiyar-jalalian-3ba9a8273/"
    telegram: "JMAHDIYARJ"
    email: "mahdiyarjalalian827@gmail.com"	

